### PR TITLE
Adds Paylod to the chart

### PR DESCRIPTION
**Pull request by davidgrenier**
I tried putting an YAxis2 and get correct scaling but couldn't get it to work as I'd hoped.

### CODE REVIEW

**Comment by theburningmonk** [comment]
mm.. maybe we don't have to squeeze them all on the same chart?

On the whole charting front, i had trouble getting FsCharting to work from a batch script since ShowChart() gets blocks when you have to use Console.ReadKey() to keep the thread alive and it blocks the pipe for FsCharting.

So I've been thinking of using FsPlot (https://github.com/TahaHachana/FsPlot) instead or use a simple HTML template like I did in Amazon.CloudWatch.Selector's CLI (https://github.com/theburningmonk/Amazon.CloudWatch.Selector/blob/develop/src/CloudWatch.Selector.Cli/Program.fs#L58-L71) so that I can have a script that will build the benchmark solutions with FAKE and then show the prompt to run benchmarks and then plot the results to HTML.

Have you had any experience with FsPlot? From this post (http://fsharp-code.blogspot.co.uk/2014/01/creating-dynamic-charts-with-fsplot.html) it looks pretty straight forward, hopefully you can also easily create multiple plots on the same page.

**Comment by davidgrenier** [comment]
Ok I found out that what I need to be able to scale the payload with a separate axis at the top is not exposed in FSharp.Charting... I presume I'd have to fix that and send a pull request to FSharp.Charting.

About the blocking... could it have anything to do with FSharp.Charting.fsx's default ShowChart output?

``` fsharp
fsi.AddPrinter(fun (ch: ChartTypes.GenericChart) -> ch.ShowChart(); "(Chart)")
```

or maybe not... sounds like it's the other way around.

No experience with FsPlot either, but I'll give it a shot.

**Comment by davidgrenier** [comment]
Another option for me at least could be to start looking at Kendo Charting lib and start working on implementing the WebSharper extension since we have both licences at work and I'm maintaining the following:

https://github.com/davidgrenier/Kendo

Not sure if this could end up being usable by your project though as this requires the WebSharper compiler, etc.

**Comment by davidgrenier** [comment]
I see FsPlot is using Funscript to hoist the F# code into the browser... that's pretty neat.

**Comment by theburningmonk** [comment]
I'm not keen on adding dependencies like Kendo UI, especially if licenses are involved. It seems overkill to just plot a couple of charts on a webpage.

**Comment by davidgrenier** [comment]
Indeed and it's a lot more work.

From the get go I'd stick to FSharp.Charting to be honest... also that you
can probably look into it and perhaps prevent the blocking via a fix to
FSharp.Charting anyway.

**Pull request merged**
