### PR TITLE
Addition of BinaryReader + fix to a typo

### PR DESCRIPTION
**Pull request by davidgrenier**
My computer seems to be much slower than yours so I'm actually unclear as to how the reader performs vs the other deserialization.

It required the addition of the count of scores to the serialization/deserialization process though I don't think that would influence the result significantly.

### CODE REVIEW

**Comment by theburningmonk** [comment]
Sure, let me have a look

**Comment by theburningmonk** [comment]
Did you still have the reference issue with SimpleJson? Looking at the project again, it's actually included as part of the project, a single SimpleJson.cs file.

**Comment by davidgrenier** [comment]
I think i get what you want, will check out my repo at work and send you a pull request, will double check SimpjeJson.cs

**Comment by davidgrenier** [comment]
Hi,

I checked again, and the project fastJson isn't present in the repository...

I see the following in the solution file:

Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "fastJSON", "lib\fastJSON v1.9.6\fastJSON\fastJSON.csproj", "{207E91B1-C9F8-4913-88E1-3549EF5F3273}"

So unless you do have that project properly referenced I don't know what SimpleJson.cs is - perhaps fastJSON project isn't commited to your repo?

**Comment by davidgrenier** [comment]
Can't do anything from work, FAKE package will just not download when calling build.cmd...

**Comment by theburningmonk** [comment]
Ah, fastJson, I changed the project to use the one that's on nuget, maybe
the project is still holding onto the old ref path, will fixed that.

**Comment by theburningmonk** [comment]
just made two commits that should fix the issue with fastJson

**Comment by davidgrenier** [comment]
Ok I fetched your changes and worked from there. Removed FsPickler on SimpleObjects and made it generic like requested. Had to add some type annotation in the call to the deserializer.

Made sure the sln version looked right, let me know.

**Pull request merged**
